const ACCOUNT_STATE_REQUEST = 'ACCOUNT_STATE_REQUEST'
const ACCOUNT_STATE_RECEIVE = 'ACCOUNT_STATE_RECEIVE'
const ACCOUNT_STATE_FAILURE = 'ACCOUNT_STATE_FAILURE'

const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export default {
  ACCOUNT_STATE_REQUEST,
  ACCOUNT_STATE_RECEIVE,
  ACCOUNT_STATE_FAILURE,

  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE
}